lane :test do
  Dir.chdir("..") do
    build_site
    ensure_headers
  end
end

private_lane :build_site do
  sh "mkdocs build --clean" # to make sure building is successful
end

private_lane :ensure_headers do
  UI.message "Investigating all docs files and their headers"
  exceptions = ["docs/index.md"]

  errors = []
  Dir["docs/**/*.md"].each do |current_file|
    next if exceptions.include?(current_file)
    errors << "File '#{current_file}' doesn't start with #" unless File.read(current_file).start_with?("#")
  end
  errors.each { |e| UI.error(e) }
  UI.user_error!("At least one file doesn't start with header one (#), the first line must always be # title") unless errors.empty?
  UI.success "All doc files start with a header 👍"
end
